// seed.js — categories, vendors, listings
// Price range: $15 minimum, $800 maximum
const db = require('./db');
const bcrypt = require('bcryptjs');

const CATS = [
  { slug: 'cards',       name: 'Carding & CCs',            icon: '💳', sort: 1 },
  { slug: 'fullz',       name: 'Fullz & Bank Drops',       icon: '📇', sort: 2 },
  { slug: 'tax',         name: 'Tax Refund & FAFSA',       icon: '🧾', sort: 3 },
  { slug: 'loans',       name: 'SBA & UI Loans',           icon: '🏦', sort: 4 },
  { slug: 'spam',        name: 'Spamming Infrastructure',  icon: '📨', sort: 5 },
  { slug: 'rt',          name: 'Remote Tasks & Call Ops',  icon: '🎧', sort: 6 },
  { slug: 'cashout',     name: 'Cashout & Drops',          icon: '💰', sort: 7 },
  { slug: 'tools',       name: 'Tools & Tutorials',        icon: '🛠️', sort: 8 },
  { slug: 'logs',        name: 'Logs & Access',            icon: '🔐', sort: 9 },
  { slug: 'id',          name: 'IDs & Docs',               icon: '🪪', sort: 10 },
  { slug: 'crypto',      name: 'Crypto & Wallets',         icon: '₿',  sort: 11 },
  { slug: 'malware',     name: 'Malware & Loaders',        icon: '☣️', sort: 12 },
  { slug: 'guides',      name: 'Guides & Courses',         icon: '📚', sort: 13 },
  { slug: 'telecom',     name: 'eSIM, DID & VoIP',         icon: '📞', sort: 14 },
  { slug: 'bypass',      name: 'CAPTCHA & 2FA Bypass',     icon: '🤖', sort: 15 },
  { slug: 'cve',         name: 'CVEs & Exploits',          icon: '🐛', sort: 16 },
  { slug: 'enroll',      name: 'Enrollment & IDME',        icon: '🎓', sort: 17 },
  { slug: 'transcripts', name: 'Transcripts & Diplomas',   icon: '📜', sort: 18 },
  { slug: 'flasher',     name: 'Flashers & Fake Funds',    icon: '💵', sort: 19 },
  { slug: 'jailbreak',   name: 'Jailbreaks & Unlocks',     icon: '🔓', sort: 20 },
  { slug: 'drugs',       name: 'Drugs & Pharmaceuticals',  icon: '💊', sort: 21 },
  { slug: 'hire',        name: 'Hackers For Hire',         icon: '👤', sort: 22 },
  { slug: 'docs',        name: 'Documents & Certificates', icon: '📄', sort: 23 }
];

const upsertCat = db.prepare(
  `INSERT INTO categories (slug, name, icon, sort) VALUES (?, ?, ?, ?)
   ON CONFLICT(slug) DO UPDATE SET name = excluded.name, icon = excluded.icon, sort = excluded.sort`
);
for (const c of CATS) upsertCat.run(c.slug, c.name, c.icon, c.sort);

function ensureUser(handle, password, vendor = 0) {
  let u = db.prepare(`SELECT * FROM users WHERE handle = ?`).get(handle);
  if (u) return u;
  const hash = bcrypt.hashSync(password, 10);
  const info = db.prepare(
    `INSERT INTO users (handle, password_hash, vendor, balance) VALUES (?, ?, ?, 0)`
  ).run(handle, hash, vendor);
  return db.prepare(`SELECT * FROM users WHERE id = ?`).get(info.lastInsertRowid);
}

const v1  = ensureUser('darkbazaar',   'hunter2!!!', 1);
const v2  = ensureUser('shadowbroker', 'hunter2!!!', 1);
const v3  = ensureUser('taxkingpin',   'hunter2!!!', 1);
const v4  = ensureUser('spamfactory',  'hunter2!!!', 1);
const v5  = ensureUser('cryptovault',  'hunter2!!!', 1);
const v6  = ensureUser('zero_day',     'hunter2!!!', 1);
const v7  = ensureUser('telecom_ghost','hunter2!!!', 1);
const v8  = ensureUser('bypass_lab',   'hunter2!!!', 1);
const v9  = ensureUser('enroll_pro',   'hunter2!!!', 1);
const v10 = ensureUser('paper_mill',   'hunter2!!!', 1);
const v11 = ensureUser('cash_printer', 'hunter2!!!', 1);
const v12 = ensureUser('unlock_shop',  'hunter2!!!', 1);
const v13 = ensureUser('pharma_dark',  'hunter2!!!', 1);
const v14 = ensureUser('hire_gun',     'hunter2!!!', 1);

const LISTINGS = [
  // ─── CARDS ───────────────────────────────────────────
  { v: v1, cat: 'cards', title: 'Single US CVV — Verified Live', subtitle: 'Non-VBV, single unit',
    description: 'Single US-issued CVV card. Non-VBV BIN. Verified live against issuer before delivery. Replacement for dead on arrival within 24 hours.',
    price_usd: 15, unit: 'card', stock: 999, region: 'US', sales: 1842, rating_avg: 4.5, rating_count: 612 },
  { v: v1, cat: 'cards', title: 'US CVV — Starter Pack (10)', subtitle: 'Non-VBV, verified live',
    description: 'Fresh US CVV base, 10 units per pack. Non-VBV BINs only. Every card checked live against issuer before pack ships.',
    price_usd: 75, unit: '10 pack', stock: 128, region: 'US', sales: 412, rating_avg: 4.7, rating_count: 194 },
  { v: v1, cat: 'cards', title: 'US CVV — Fresh Base (50 pack)', subtitle: 'Non-VBV, verified live',
    description: 'Fresh CVV base, US issued. 50 units per pack. Non-VBV BINs only. Dead-on-arrival replaced within 24 hours.',
    price_usd: 320, unit: '50 pack', stock: 42, region: 'US', sales: 187, rating_avg: 4.8, rating_count: 96 },
  { v: v1, cat: 'cards', title: 'EU CVV — Fullz-grade (25 pack)', subtitle: 'Full info: DOB, SSN, MMN',
    description: 'EU CVV with full matched info — name, address, DOB, phone, MMN. 25 units. High-approval BINs preferred by EU processors.',
    price_usd: 280, unit: '25 pack', stock: 18, region: 'EU', sales: 94, rating_avg: 4.6, rating_count: 41 },
  { v: v1, cat: 'cards', title: 'Cardable Shops List — Weekly', subtitle: 'Non-3DS, low fraud score',
    description: 'Curated list of e-commerce shops with weak AVS, low fraud score, fast fulfillment. Includes recommended BIN per shop, proxy notes, and success-rate history.',
    price_usd: 45, unit: 'subscription', stock: 999, region: 'WW', sales: 612, rating_avg: 4.9, rating_count: 244 },
  { v: v1, cat: 'cards', title: 'Fullz + CVV Combo — 20 pack', subtitle: 'Matched card and identity',
    description: 'Card number matched to full identity: SSN, DOB, address, phone. 20 units. Best for shops requiring AVS and CVV together.',
    price_usd: 380, unit: '20 pack', stock: 27, region: 'US', sales: 122, rating_avg: 4.7, rating_count: 58 },
  { v: v1, cat: 'cards', title: 'BIN List — High Approval', subtitle: 'Updated weekly',
    description: 'Curated BIN list of high-approval issuers. Includes region, card type, AVS requirements, and 3DS status. Updated weekly.',
    price_usd: 25, unit: 'list', stock: 999, region: 'WW', sales: 388, rating_avg: 4.6, rating_count: 156 },

  // ─── FULLZ ───────────────────────────────────────────
  { v: v2, cat: 'fullz', title: 'Single US Fullz — Basic', subtitle: 'SSN + DOB + address',
    description: 'Single US fullz. Includes SSN, DOB, current address, phone number, and MMN. Verified within 7 days. Basic tier.',
    price_usd: 20, unit: 'fullz', stock: 999, region: 'US', sales: 892, rating_avg: 4.4, rating_count: 348 },
  { v: v2, cat: 'fullz', title: 'US Fullz w/ Bank Login — 50 pack', subtitle: 'Full ID + bank combo',
    description: 'US fullz with matched bank login. 50 units. SSN, DOB, address history, bank username, password, and security answers.',
    price_usd: 750, unit: '50 pack', stock: 22, region: 'US', sales: 88, rating_avg: 4.7, rating_count: 35 },
  { v: v2, cat: 'fullz', title: 'Bank Drops — Chime / Varo / SoFi', subtitle: 'Pre-verified, 24h hold',
    description: 'Bank drops at US regional banks. Chime, Varo, SoFi, Current. Pre-verified, ready for incoming transfers. 24-48h hold before first outbound.',
    price_usd: 220, unit: 'account', stock: 46, region: 'US', sales: 213, rating_avg: 4.5, rating_count: 78 },
  { v: v2, cat: 'fullz', title: 'Business Fullz — LLC + EIN + Bank', subtitle: 'SBA-ready package',
    description: 'Aged LLC with EIN, business bank account, corporate credit file. 2-5 years seasoned. Formation docs included.',
    price_usd: 780, unit: 'package', stock: 8, region: 'US', sales: 31, rating_avg: 4.8, rating_count: 14 },
  { v: v2, cat: 'fullz', title: 'Fullz — Aged 65+ (10 pack)', subtitle: 'Senior-tier identity',
    description: 'Aged fullz, 65+ demographic. Clean credit history, high approval rates on credit products. 10 units per pack.',
    price_usd: 280, unit: '10 pack', stock: 35, region: 'US', sales: 156, rating_avg: 4.6, rating_count: 71 },
  { v: v2, cat: 'fullz', title: 'Healthcare Fullz — Insurance Match', subtitle: 'Insurance + medical',
    description: 'Fullz with active healthcare insurance information. Includes member ID, policy details, provider network. 5 units per pack.',
    price_usd: 350, unit: '5 pack', stock: 22, region: 'US', sales: 68, rating_avg: 4.5, rating_count: 29 },
  { v: v2, cat: 'fullz', title: 'Fullz Sample — Single', subtitle: 'Preview tier',
    description: 'Single fullz for preview purposes. Basic info only: SSN, DOB, state. No bank info. Verified.',
    price_usd: 15, unit: 'sample', stock: 999, region: 'US', sales: 412, rating_avg: 4.3, rating_count: 178 },

  // ─── TAX ─────────────────────────────────────────────
  { v: v3, cat: 'tax', title: 'Tax Refund Package — US (Single)', subtitle: 'W2 + ID + Bank drop',
    description: 'Complete tax refund package. Matched W2, government ID, SSN, bank drop. Pre-verified. Ready for e-file.',
    price_usd: 480, unit: 'package', stock: 35, region: 'US', sales: 142, rating_avg: 4.6, rating_count: 61 },
  { v: v3, cat: 'tax', title: 'FAFSA Student Aid Kit', subtitle: 'Full identity + enrollment',
    description: 'Complete FAFSA kit. Full identity matching an enrolled student, tax returns, enrollment verification letter, bank drop.',
    price_usd: 620, unit: 'package', stock: 19, region: 'US', sales: 76, rating_avg: 4.7, rating_count: 28 },
  { v: v3, cat: 'tax', title: 'Tax Prep Software Access — Bulk API', subtitle: 'Drake, Lacerte, ProSeries',
    description: 'Bulk access to professional tax prep software APIs. Batch e-file from multiple prepared returns. Rotating EFIN + PTIN included.',
    price_usd: 790, unit: 'license', stock: 5, region: 'US', sales: 22, rating_avg: 4.4, rating_count: 9 },
  { v: v3, cat: 'tax', title: 'Tax Refund Package — Bulk 3', subtitle: '3 complete sets',
    description: 'Three complete tax refund packages. Matched identities, W2s, and bank drops. Bulk discount applied.',
    price_usd: 750, unit: '3 pack', stock: 12, region: 'US', sales: 41, rating_avg: 4.7, rating_count: 18 },
  { v: v3, cat: 'tax', title: 'W2 Generator — Any Employer', subtitle: 'PDF template',
    description: 'W2 generator with editable employer details, wages, and tax withholding. PDF output. Print-ready.',
    price_usd: 35, unit: 'license', stock: 999, region: 'US', sales: 244, rating_avg: 4.5, rating_count: 98 },

  // ─── LOANS ───────────────────────────────────────────
  { v: v2, cat: 'loans', title: 'SBA Loan Fraud Kit — Full Pipeline', subtitle: 'Aged entity + bank + docs',
    description: 'Complete SBA loan pipeline. Aged entity, EIN, business bank account, forged tax returns (3 years), forged financials, forged lease.',
    price_usd: 800, unit: 'kit', stock: 6, region: 'US', sales: 18, rating_avg: 4.8, rating_count: 11 },
  { v: v3, cat: 'loans', title: 'UI Claim Bundle — Multi-State', subtitle: 'Identity + employment match',
    description: 'Unemployment insurance claim bundle. Identity matched to employment in 5 states. Automated claim filing via state portal.',
    price_usd: 380, unit: 'package', stock: 40, region: 'US', sales: 189, rating_avg: 4.5, rating_count: 72 },
  { v: v3, cat: 'loans', title: 'PPP / EIDL Legacy Package', subtitle: 'Recovered accounts',
    description: 'Recovered PPP / EIDL accounts from archived portfolios. Dormant and reactivatable. Original application + docs included.',
    price_usd: 650, unit: 'package', stock: 11, region: 'US', sales: 44, rating_avg: 4.3, rating_count: 19 },
  { v: v3, cat: 'loans', title: 'Personal Loan Application Kit', subtitle: 'Complete doc set',
    description: 'Personal loan application package. Matched identity, pay stubs, employment verification, tax returns.',
    price_usd: 340, unit: 'kit', stock: 55, region: 'US', sales: 211, rating_avg: 4.6, rating_count: 89 },
  { v: v3, cat: 'loans', title: 'Pay Stub Generator — Any State', subtitle: 'PDF + print-ready',
    description: 'Pay stub generator. Any state, any employer, any pay frequency. PDF and print-ready output. Tax withholding calculations included.',
    price_usd: 25, unit: 'license', stock: 999, region: 'US', sales: 512, rating_avg: 4.6, rating_count: 214 },

  // ─── SPAM ────────────────────────────────────────────
  { v: v4, cat: 'spam', title: 'Bulk SMTP — High Inbox Rotation', subtitle: 'Aged domains, DKIM/SPF',
    description: 'Bulk SMTP service. Aged domains, DKIM/SPF/DMARC configured, warmed IP rotation. 100k/month send capacity.',
    price_usd: 380, unit: 'month', stock: 999, region: 'WW', sales: 244, rating_avg: 4.6, rating_count: 88 },
  { v: v4, cat: 'spam', title: 'Phishing Kit — 12 Templates', subtitle: 'O365, Gmail, Coinbase, Chase…',
    description: '12 phishing landing page templates. Microsoft 365, Google Workspace, Coinbase, Chase, Wells Fargo, BoA, USAA, PayPal, Venmo, DHL, FedEx, IRS.',
    price_usd: 260, unit: 'kit', stock: 999, region: 'WW', sales: 512, rating_avg: 4.8, rating_count: 217 },
  { v: v4, cat: 'spam', title: 'SMS Blaster — 5k/hour', subtitle: 'Twilio bypass + SIM farm',
    description: 'SMS blaster service. 5k messages/hour. Twilio bypass path, backup SIM farm path. Sender ID spoofing. Delivery reports.',
    price_usd: 550, unit: 'month', stock: 999, region: 'WW', sales: 178, rating_avg: 4.5, rating_count: 63 },
  { v: v4, cat: 'spam', title: 'Cold Email Infra — Full Stack', subtitle: 'Domains + inboxes + warmup',
    description: 'Complete cold email infrastructure. 50 aged domains, 500 inboxes, warmup, reply handling, rotation controller.',
    price_usd: 750, unit: 'setup', stock: 999, region: 'WW', sales: 89, rating_avg: 4.7, rating_count: 34 },
  { v: v4, cat: 'spam', title: 'Call Bombing Service', subtitle: 'Voice flood, 500/min',
    description: 'Voice flood service targeting a specified number. 500 calls/min sustained. Rotating caller IDs.',
    price_usd: 160, unit: 'per hour', stock: 999, region: 'WW', sales: 301, rating_avg: 4.4, rating_count: 118 },
  { v: v4, cat: 'spam', title: 'Email Bombing Kit', subtitle: 'Subscription floods',
    description: 'Subscription-flood email bomber. Target inbox gets thousands of legit confirmation emails per hour. Curated signup list included.',
    price_usd: 180, unit: 'kit', stock: 999, region: 'WW', sales: 187, rating_avg: 4.5, rating_count: 74 },
  { v: v4, cat: 'spam', title: 'Single SMS Blast — 100 msgs', subtitle: 'Test tier',
    description: 'Test blast of 100 SMS messages. Sender ID spoofing included. Delivery reports. Test before committing to monthly plan.',
    price_usd: 30, unit: 'per 100', stock: 999, region: 'WW', sales: 412, rating_avg: 4.4, rating_count: 156 },
  { v: v4, cat: 'spam', title: 'cPanel SMTP Access — Verified', subtitle: 'Bulk send ready',
    description: 'Verified cPanel SMTP access. Full credentials for cPanel accounts with send authority. Ready for bulk outbound. Rotating inventory.',
    price_usd: 90, unit: 'account', stock: 88, region: 'WW', sales: 456, rating_avg: 4.5, rating_count: 189 },
  { v: v4, cat: 'spam', title: 'cPanel / WHM Access — Admin', subtitle: 'Full server access',
    description: 'Admin-level cPanel/WHM credentials. Full server access, email account creation, DKIM/SPF control. Aged servers preferred.',
    price_usd: 320, unit: 'access', stock: 24, region: 'WW', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v4, cat: 'spam', title: 'cPanel Access — Bulk 50', subtitle: 'Wholesale tier',
    description: 'Bulk cPanel access. 50 verified accounts per pack. Mixed providers. Ready for outbound campaigns.',
    price_usd: 700, unit: '50 pack', stock: 14, region: 'WW', sales: 88, rating_avg: 4.6, rating_count: 34 },

  // ─── REMOTE TASKS ────────────────────────────────────
  { v: v4, cat: 'rt', title: 'Remote Caller Ops — Verified Team', subtitle: '10 callers, EN/ES',
    description: 'Managed remote caller operation. 10 trained callers, fluent EN/ES, warm + cold scripts, CRM integration, call recording.',
    price_usd: 780, unit: 'month', stock: 12, region: 'WW', sales: 41, rating_avg: 4.6, rating_count: 17 },
  { v: v4, cat: 'rt', title: 'Remote VA Team — Bank Trained', subtitle: 'US/UK accent, 20 seats',
    description: 'Remote VA team with bank fraud and call center training. 20 seats, US/UK accent, warm transfer, screen-share, remote desktop.',
    price_usd: 720, unit: 'month', stock: 8, region: 'WW', sales: 27, rating_avg: 4.5, rating_count: 13 },
  { v: v4, cat: 'rt', title: 'Task Runner Network — 500+ Workers', subtitle: 'CAPTCHA, verification, KYC',
    description: 'Task runner network with 500+ micro-workers across 12 countries. CAPTCHA, KYC video verify, phone verify, address confirm. Per-task pricing.',
    price_usd: 75, unit: 'per 100 tasks', stock: 9999, region: 'WW', sales: 388, rating_avg: 4.7, rating_count: 141 },
  { v: v4, cat: 'rt', title: 'Bulk Account Verification Service', subtitle: 'Bank + email + phone',
    description: 'Bulk verification. Bank micro-deposits, email OTP, phone OTP, SMS confirmation. Batch up to 1000 per order. 24h turnaround.',
    price_usd: 140, unit: 'per 1k', stock: 999, region: 'WW', sales: 156, rating_avg: 4.6, rating_count: 62 },
  { v: v4, cat: 'rt', title: 'CAPTCHA Solving — 1k Bundle', subtitle: 'Human workers',
    description: 'CAPTCHA solving via human workers. reCAPTCHA v2, v3, hCaptcha, image challenges. 1000 solutions per bundle. 24h turnaround.',
    price_usd: 40, unit: 'per 1k', stock: 999, region: 'WW', sales: 622, rating_avg: 4.6, rating_count: 254 },

  // ─── CASHOUT ─────────────────────────────────────────
  { v: v1, cat: 'cashout', title: 'Cashout — WU / MoneyGram', subtitle: '20-40% fee',
    description: 'Cashout service for carding and ATO proceeds. Western Union, MoneyGram, bank wire, crypto OTC. Fee 20-40%. Minimum $500.',
    price_usd: 500, unit: 'per transaction', stock: 999, region: 'WW', sales: 144, rating_avg: 4.6, rating_count: 58 },
  { v: v1, cat: 'cashout', title: 'Cash App / Venmo / Zelle Drops', subtitle: 'Aged, verified, US',
    description: 'Aged Cash App, Venmo, and Zelle drops. Verified US. Ready for incoming transfers. $250-5k per transfer safe size.',
    price_usd: 180, unit: 'account', stock: 62, region: 'US', sales: 271, rating_avg: 4.7, rating_count: 108 },
  { v: v5, cat: 'cashout', title: 'Crypto OTC — 15 Countries', subtitle: 'No KYC, 1% spread',
    description: 'OTC desk for crypto to fiat in 15 countries. No KYC. 1% spread XMR/BTC. Same-day settlement.',
    price_usd: 150, unit: 'min deposit', stock: 999, region: 'WW', sales: 199, rating_avg: 4.8, rating_count: 82 },
  { v: v1, cat: 'cashout', title: 'Gift Card Cashout Service', subtitle: 'Amazon, Apple, Steam',
    description: 'Gift card liquidation. Amazon, Apple, Steam, Google Play, Walmart. 55-70% payout. Volume rates available.',
    price_usd: 100, unit: 'min order', stock: 999, region: 'WW', sales: 388, rating_avg: 4.5, rating_count: 152 },
  { v: v1, cat: 'cashout', title: 'Gift Card — Single Cleanout', subtitle: 'Entry tier',
    description: 'Single gift card cashout. Test the service before committing. Minimum $15 card. 55% payout on $15.',
    price_usd: 15, unit: 'per card', stock: 999, region: 'WW', sales: 512, rating_avg: 4.3, rating_count: 187 },

  // ─── TOOLS ───────────────────────────────────────────
  { v: v1, cat: 'tools', title: 'ANTIDETECT Browser — 12 Profiles', subtitle: 'Fingerprint-spoofed',
    description: 'Antidetect browser with 12 pre-configured profiles. Canvas, WebGL, fonts, timezone, language randomized. Proxy manager included.',
    price_usd: 220, unit: 'license', stock: 999, region: 'WW', sales: 458, rating_avg: 4.8, rating_count: 194 },
  { v: v6, cat: 'tools', title: 'OTP Bypass Suite — SMS/Call/Email', subtitle: 'Realtime interception',
    description: 'OTP bypass suite covering SMS, voice call, and email OTP. SIM swap, SS7, and SIM-box paths. Realtime panel. Updates biweekly.',
    price_usd: 780, unit: 'license', stock: 42, region: 'WW', sales: 76, rating_avg: 4.6, rating_count: 31 },
  { v: v6, cat: 'tools', title: 'Fullz-to-Cash Pipeline — Auto', subtitle: 'End-to-end automation',
    description: 'Fullz ingestion → bank drop selection → card generation → shop purchase → cashout routing. Configurable per vertical. Monitoring dashboard.',
    price_usd: 800, unit: 'setup', stock: 5, region: 'WW', sales: 14, rating_avg: 4.7, rating_count: 8 },
  { v: v1, cat: 'tools', title: 'Proxy Pack — Residential, 5 Countries', subtitle: 'Rotating, sticky option',
    description: 'Residential proxy pack covering 5 countries. Rotating and sticky options. 50 GB traffic included. SOCKS5 and HTTP.',
    price_usd: 180, unit: 'month', stock: 999, region: 'WW', sales: 344, rating_avg: 4.6, rating_count: 128 },
  { v: v1, cat: 'tools', title: 'Fingerprint Spoofer — Standalone', subtitle: 'Windows 10/11',
    description: 'Standalone fingerprint spoofer for Windows. Bypasses Canvas, WebGL, AudioContext, fonts, and screen metrics. Kernel-level option available.',
    price_usd: 210, unit: 'license', stock: 999, region: 'WW', sales: 267, rating_avg: 4.7, rating_count: 102 },
  { v: v6, cat: 'tools', title: 'Bulk Email Validator', subtitle: '1M/day throughput',
    description: 'Email validation. 1M addresses/day. SMTP-level verification, catch-all detection, role-account filtering. API access included.',
    price_usd: 160, unit: 'month', stock: 999, region: 'WW', sales: 178, rating_avg: 4.5, rating_count: 71 },
  { v: v6, cat: 'tools', title: 'Proxy List — Free Sample', subtitle: 'Preview tier',
    description: 'Sample proxy list. 10 HTTP/SOCKS5 proxies. Preview before subscribing to full pack. Mixed quality.',
    price_usd: 15, unit: 'sample', stock: 999, region: 'WW', sales: 612, rating_avg: 4.2, rating_count: 288 },

  // ─── LOGS ────────────────────────────────────────────
  { v: v2, cat: 'logs', title: 'Stealer Logs — Fresh Daily', subtitle: '10k+ entries/day',
    description: 'Fresh stealer logs from live infections. 10k+ entries/day. Filter by country, browser, crypto wallet presence, corporate SSO.',
    price_usd: 120, unit: 'per 1k logs', stock: 999, region: 'WW', sales: 522, rating_avg: 4.7, rating_count: 221 },
  { v: v2, cat: 'logs', title: 'Corporate VPN / SSO Access', subtitle: 'Fortune 500, verified',
    description: 'Verified corporate VPN and SSO access. Fortune 500 targets. Session cookies, MFA bypass note, lateral movement guide.',
    price_usd: 780, unit: 'access', stock: 24, region: 'WW', sales: 58, rating_avg: 4.8, rating_count: 22 },
  { v: v2, cat: 'logs', title: 'Email Inbox Access — Bulk', subtitle: 'Aged, verified, WW',
    description: 'Bulk email inbox access. Aged accounts, verified, worldwide mix. Recovery info for lockout resistance.',
    price_usd: 90, unit: 'per 100', stock: 999, region: 'WW', sales: 388, rating_avg: 4.5, rating_count: 152 },
  { v: v2, cat: 'logs', title: 'Crypto Wallet Logs — Bulk', subtitle: 'Seed + keystore',
    description: 'Crypto wallet logs. Seed phrase, keystore file, password, wallet type. Filter by balance range. 100 units per pack.',
    price_usd: 320, unit: '100 pack', stock: 42, region: 'WW', sales: 187, rating_avg: 4.6, rating_count: 78 },
  { v: v2, cat: 'logs', title: 'Stealer Log — Single Entry', subtitle: 'Preview tier',
    description: 'Single stealer log entry. Random country. Basic credential extraction. Test the quality before buying bulk.',
    price_usd: 15, unit: 'log', stock: 999, region: 'WW', sales: 892, rating_avg: 4.3, rating_count: 342 },

  // ─── IDs ─────────────────────────────────────────────
  { v: v3, cat: 'id', title: 'US Driver License — 30 States', subtitle: 'Scannable, hologram',
    description: 'US driver licenses in 30 states. Scannable, UV, hologram. Ships with matching utility bill and secondary doc. Stealth shipping WW.',
    price_usd: 220, unit: 'ID', stock: 84, region: 'US', sales: 231, rating_avg: 4.6, rating_count: 91 },
  { v: v3, cat: 'id', title: 'SSN + Card + DOB Set — Bulk', subtitle: 'Matched US fullz core',
    description: 'Bulk matched sets. SSN, card number, DOB. 500 units per pack. US issued, verified live within 7 days. Replacement for DOA.',
    price_usd: 680, unit: '500 pack', stock: 44, region: 'US', sales: 144, rating_avg: 4.6, rating_count: 61 },
  { v: v3, cat: 'id', title: 'Passport + Visa Combo — WW', subtitle: '40+ countries',
    description: 'Passports and visa combinations from 40+ countries. Biometrics page and secondary support. Stealth WW shipping.',
    price_usd: 340, unit: 'set', stock: 128, region: 'WW', sales: 167, rating_avg: 4.5, rating_count: 74 },
  { v: v3, cat: 'id', title: 'Utility Bill Generator — Any State', subtitle: 'PDF + print-ready',
    description: 'Utility bill generator covering all 50 US states. Address lookup included. PDF and print-ready output.',
    price_usd: 120, unit: 'license', stock: 999, region: 'US', sales: 244, rating_avg: 4.7, rating_count: 98 },
  { v: v3, cat: 'id', title: 'ID Template — Photoshop PSD', subtitle: 'Entry tier',
    description: 'Blank ID template in Photoshop format. Editable layers for name, DOB, address, photo. Single state template.',
    price_usd: 20, unit: 'template', stock: 999, region: 'US', sales: 388, rating_avg: 4.4, rating_count: 156 },

  // ─── CRYPTO ──────────────────────────────────────────
  { v: v5, cat: 'crypto', title: 'Crypto Wallet — Pre-funded', subtitle: 'Multiple chains',
    description: 'Pre-funded crypto wallets. BTC, ETH, USDT, XMR. Balances vary from $200 to $2000 depending on tier. Delivery includes seed phrase and private key.',
    price_usd: 480, unit: 'wallet', stock: 38, region: 'WW', sales: 98, rating_avg: 4.5, rating_count: 42 },
  { v: v5, cat: 'crypto', title: 'KYC-Verified Exchange Accounts', subtitle: 'Binance, Kraken, Coinbase',
    description: 'Fully KYC-verified exchange accounts. Binance, Kraken, Coinbase, KuCoin. Includes ID docs, selfie verification, bank linking. Aged 3-12 months.',
    price_usd: 780, unit: 'account', stock: 46, region: 'WW', sales: 133, rating_avg: 4.7, rating_count: 56 },
  { v: v5, cat: 'crypto', title: 'USDT Laundry Service', subtitle: 'Tumbling + mixing',
    description: 'USDT and BTC laundry. Mixing, tumbling, chain-hopping. Output to fresh wallets with no on-chain linkage. 3-8% fee.',
    price_usd: 200, unit: 'min deposit', stock: 999, region: 'WW', sales: 122, rating_avg: 4.5, rating_count: 51 },
  { v: v5, cat: 'crypto', title: 'NFT Wash Trading Bot', subtitle: 'Multi-marketplace',
    description: 'NFT wash trading bot supporting OpenSea, Blur, LooksRare, Rarible. Volume generation, price manipulation, floor management.',
    price_usd: 550, unit: 'license', stock: 999, region: 'WW', sales: 87, rating_avg: 4.4, rating_count: 34 },
  { v: v5, cat: 'crypto', title: 'Wallet Seed Phrase — Single', subtitle: 'Entry tier',
    description: 'Single crypto wallet seed phrase with associated private key. Balances vary. Random chain from BTC, ETH, USDT.',
    price_usd: 15, unit: 'seed', stock: 999, region: 'WW', sales: 122, rating_avg: 4.2, rating_count: 48 },

  // ─── MALWARE ─────────────────────────────────────────
  { v: v6, cat: 'malware', title: 'Stealer — Windows Build', subtitle: 'Browser + crypto + FTP',
    description: 'Windows stealer. Browsers (Chrome, Firefox, Edge, Brave, Opera), crypto wallets (20+), FTP clients, Discord tokens, Telegram sessions. FUD option.',
    price_usd: 480, unit: 'build', stock: 999, region: 'WW', sales: 312, rating_avg: 4.6, rating_count: 131 },
  { v: v6, cat: 'malware', title: 'RAT — Cross-Platform', subtitle: 'Win / Mac / Linux',
    description: 'Remote access tool. Full remote control, keylogging, screen capture, webcam, file transfer, persistence. Win/Mac/Linux. Encrypted C2.',
    price_usd: 720, unit: 'license', stock: 999, region: 'WW', sales: 189, rating_avg: 4.7, rating_count: 84 },
  { v: v6, cat: 'malware', title: 'Ransomware — Custom Build', subtitle: 'AES-256 + RSA-4096',
    description: 'Custom ransomware builder. AES-256 file encryption, RSA-4096 key exchange, shadow copy deletion, extension targeting. Tor payment portal.',
    price_usd: 800, unit: 'build', stock: 42, region: 'WW', sales: 41, rating_avg: 4.5, rating_count: 18 },
  { v: v6, cat: 'malware', title: 'Cryptominer — Silent Install', subtitle: 'XMR, cross-platform',
    description: 'Silent XMR miner. CPU/GPU hybrid. Windows/Linux installers. Persistence and watchdog included. Configurable pool and wallet.',
    price_usd: 340, unit: 'license', stock: 999, region: 'WW', sales: 178, rating_avg: 4.5, rating_count: 72 },
  { v: v6, cat: 'malware', title: 'Loader — Windows Defender Bypass', subtitle: 'FUD, signed',
    description: 'FUD loader for Windows. Signed cert, Defender bypass, AMSI patch, ETW patch. Loads arbitrary payloads into memory. Support included.',
    price_usd: 780, unit: 'license', stock: 88, region: 'WW', sales: 92, rating_avg: 4.6, rating_count: 39 },
  { v: v6, cat: 'malware', title: 'Keylogger — Basic Windows', subtitle: 'Entry tier',
    description: 'Basic Windows keylogger. Keystrokes, clipboard, active window titles. Logs to local file or exfil endpoint. No AV evasion.',
    price_usd: 15, unit: 'build', stock: 999, region: 'WW', sales: 512, rating_avg: 4.2, rating_count: 178 },
  { v: v6, cat: 'malware', title: 'RAT — Windows Basic', subtitle: 'Entry tier',
    description: 'Basic Windows RAT. Remote shell, file browser, screen view. Unencrypted C2. For lab use or beginners.',
    price_usd: 45, unit: 'build', stock: 999, region: 'WW', sales: 388, rating_avg: 4.3, rating_count: 142 },
  { v: v6, cat: 'malware', title: 'RAT — Android APK', subtitle: 'Full-featured',
    description: 'Android RAT delivered as APK. Full device control: SMS, contacts, GPS, camera, mic, files, keylogging, screen capture. Persistence and C2 panel.',
    price_usd: 320, unit: 'build', stock: 88, region: 'WW', sales: 211, rating_avg: 4.6, rating_count: 82 },
  { v: v6, cat: 'malware', title: 'RAT — macOS Build', subtitle: 'Signed, persistent',
    description: 'macOS RAT. Signed binary, LaunchAgent persistence, screen capture, file transfer, webcam, keylogging. Encrypted C2.',
    price_usd: 620, unit: 'build', stock: 32, region: 'WW', sales: 87, rating_avg: 4.5, rating_count: 34 },
  { v: v6, cat: 'malware', title: 'Crypter — FUD Builder', subtitle: 'Windows executables',
    description: 'FUD crypter for Windows. Scans against 30+ AV engines. Encrypts payload, generates unique stub per build. Includes unpacker for updates.',
    price_usd: 650, unit: 'license', stock: 44, region: 'WW', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v6, cat: 'malware', title: 'Crypter — Basic XOR', subtitle: 'Entry tier',
    description: 'Basic XOR crypter. Encrypts payload with rotating XOR key. Evades signature detection on un-updated AV. Simple stub.',
    price_usd: 20, unit: 'build', stock: 999, region: 'WW', sales: 412, rating_avg: 4.2, rating_count: 156 },
  { v: v6, cat: 'malware', title: 'Crypter — Private FUD', subtitle: 'Custom stub per client',
    description: 'Private FUD crypter. Custom stub built per client. Scans against all major AVs including Defender, Kaspersky, Bitdefender. Weekly re-encryption.',
    price_usd: 800, unit: 'license', stock: 12, region: 'WW', sales: 34, rating_avg: 4.8, rating_count: 14 },
  { v: v6, cat: 'malware', title: 'Trojan — Banking Overlay', subtitle: 'Windows, 40+ banks',
    description: 'Banking trojan with overlay injection. Supports 40+ banks (US, EU, UK, AU). Web injection, form grabbing, SMS intercept, 2FA bypass modules.',
    price_usd: 780, unit: 'build', stock: 22, region: 'WW', sales: 67, rating_avg: 4.7, rating_count: 28 },
  { v: v6, cat: 'malware', title: 'Trojan — Discord Token Grabber', subtitle: 'Windows, silent',
    description: 'Discord token grabber. Extracts tokens from local storage, browsers, and running processes. Silent install. Exfil via webhook.',
    price_usd: 60, unit: 'build', stock: 999, region: 'WW', sales: 512, rating_avg: 4.5, rating_count: 217 },
  { v: v6, cat: 'malware', title: 'Trojan — Crypto Clipper', subtitle: 'Multi-chain',
    description: 'Crypto clipper. Monitors clipboard for wallet addresses, replaces with attacker address. Supports BTC, ETH, USDT, XMR, LTC. Window swap technique.',
    price_usd: 120, unit: 'build', stock: 999, region: 'WW', sales: 344, rating_avg: 4.6, rating_count: 128 },
  { v: v6, cat: 'malware', title: 'Trojan — Backdoor Shell', subtitle: 'Cross-platform',
    description: 'Cross-platform backdoor shell. C2 beacon, encrypted traffic, reverse shell, file transfer, persistence. Windows, Linux, macOS builds.',
    price_usd: 240, unit: 'build', stock: 142, region: 'WW', sales: 178, rating_avg: 4.6, rating_count: 71 },
  { v: v6, cat: 'malware', title: 'Worm — Self-Spreading', subtitle: 'Windows, network',
    description: 'Self-spreading worm. Windows targets via SMB, EternalBlue-style exploits, USB autorun. Includes payload drop and persistence.',
    price_usd: 520, unit: 'build', stock: 44, region: 'WW', sales: 76, rating_avg: 4.5, rating_count: 31 },
  { v: v6, cat: 'malware', title: 'Botnet Client — DDoS', subtitle: 'Multi-vector',
    description: 'DDoS botnet client. Multi-vector attacks (HTTP flood, SYN, UDP, DNS amplification). Encrypted C2. Windows and Linux binaries.',
    price_usd: 420, unit: 'client', stock: 128, region: 'WW', sales: 133, rating_avg: 4.6, rating_count: 56 },
  { v: v6, cat: 'malware', title: 'Botnet Panel — Full C2', subtitle: 'Web-based panel',
    description: 'Botnet command & control panel. Web UI, multi-user support, statistics dashboard, live bot map, attack scheduler, custom payloads.',
    price_usd: 780, unit: 'panel', stock: 8, region: 'WW', sales: 22, rating_avg: 4.7, rating_count: 9 },

  // ─── GUIDES ──────────────────────────────────────────
  { v: v6, cat: 'guides', title: 'Carding Masterclass — Video Course', subtitle: '12 hours, EN/ES',
    description: 'Full carding masterclass. 12 hours of video. Covers BINs, carding shops, cashout, OPSEC. English and Spanish narration.',
    price_usd: 480, unit: 'course', stock: 999, region: 'WW', sales: 234, rating_avg: 4.7, rating_count: 98 },
  { v: v6, cat: 'guides', title: 'SBA Loan Application Playbook', subtitle: 'Step-by-step, updated',
    description: 'Complete SBA loan application playbook. Document templates, application timeline, bank selection, common rejection pitfalls.',
    price_usd: 620, unit: 'guide', stock: 999, region: 'US', sales: 76, rating_avg: 4.6, rating_count: 33 },
  { v: v6, cat: 'guides', title: 'Crypto Mixing & Laundering Guide', subtitle: 'On-chain OPSEC',
    description: 'Comprehensive crypto laundry guide. Chain-hopping, tumblers, DEX swaps, cross-chain bridges. On-chain OPSEC. Live examples.',
    price_usd: 550, unit: 'guide', stock: 999, region: 'WW', sales: 122, rating_avg: 4.7, rating_count: 55 },
  { v: v6, cat: 'guides', title: 'OPSEC Pack — Tor, VPN, Qubes', subtitle: 'Full setup walkthrough',
    description: 'Complete OPSEC pack. Tor config, VPN chaining, Qubes OS setup, encrypted messaging, dead-man switches. Scripts and configs.',
    price_usd: 340, unit: 'guide', stock: 999, region: 'WW', sales: 201, rating_avg: 4.8, rating_count: 87 },
  { v: v6, cat: 'guides', title: 'OPSEC Starter — Single PDF', subtitle: 'Entry tier',
    description: 'Starter OPSEC PDF. Tor installation, VPN setup basics, encrypted email. 20-page walkthrough for beginners.',
    price_usd: 15, unit: 'PDF', stock: 999, region: 'WW', sales: 892, rating_avg: 4.4, rating_count: 342 },

  // ─── TELECOM / eSIM / DID / SIP / VOIP ───────────────
  { v: v7, cat: 'telecom', title: 'eSIM — Single Verified', subtitle: 'US number, activation ready',
    description: 'Single verified eSIM with US number. Activation QR ready. Carrier-issued, works with iPhone XS+, Pixel 3+, Samsung S20+. Data and SMS included.',
    price_usd: 25, unit: 'eSIM', stock: 999, region: 'US', sales: 892, rating_avg: 4.6, rating_count: 342 },
  { v: v7, cat: 'telecom', title: 'eSIM — Bulk 20 (US Numbers)', subtitle: 'Wholesale, verified',
    description: 'Bulk eSIM pack. 20 US-numbered eSIMs. All carrier-issued and verified. QR codes delivered in zip. Ready for verification use.',
    price_usd: 380, unit: '20 pack', stock: 44, region: 'US', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v7, cat: 'telecom', title: 'eSIM — EU Roaming', subtitle: 'Multi-country',
    description: 'EU roaming eSIM. Works across 30+ European countries. Data, SMS, and voice. Carrier-issued. QR delivery.',
    price_usd: 45, unit: 'eSIM', stock: 128, region: 'EU', sales: 244, rating_avg: 4.5, rating_count: 98 },
  { v: v7, cat: 'telecom', title: 'eSIM — UK Number', subtitle: 'O2, Vodafone, EE',
    description: 'UK eSIM with major carrier number. O2, Vodafone, or EE. Inbound SMS and calls. Data plan included.',
    price_usd: 40, unit: 'eSIM', stock: 88, region: 'UK', sales: 178, rating_avg: 4.5, rating_count: 71 },
  { v: v7, cat: 'telecom', title: 'DID Number — US Local', subtitle: 'SIP trunk ready',
    description: 'US local DID number. Ready for SIP trunk connection. Inbound and outbound. Full call routing. Compatible with Asterisk, FreeSWITCH, 3CX.',
    price_usd: 30, unit: 'DID', stock: 999, region: 'US', sales: 456, rating_avg: 4.6, rating_count: 178 },
  { v: v7, cat: 'telecom', title: 'DID Number — Bulk 25 (US)', subtitle: 'Multi-area code',
    description: 'Bulk DID pack. 25 US numbers across mixed area codes. SIP trunk credentials included. Ready for concurrent calls.',
    price_usd: 450, unit: '25 pack', stock: 34, region: 'US', sales: 88, rating_avg: 4.7, rating_count: 34 },
  { v: v7, cat: 'telecom', title: 'DID Number — UK / CA / AU', subtitle: 'International local',
    description: 'International DID numbers. UK, Canada, and Australia. SIP trunk ready. Full inbound/outbound. Port to your own PBX.',
    price_usd: 55, unit: 'DID', stock: 244, region: 'WW', sales: 211, rating_avg: 4.6, rating_count: 87 },
  { v: v7, cat: 'telecom', title: 'SIP Trunk — Full Access', subtitle: 'Unlimited concurrent',
    description: 'Full SIP trunk. Unlimited concurrent channels. US and international dialing. Inbound DIDs included. Works with Asterisk, FreeSWITCH, Kamailio.',
    price_usd: 280, unit: 'trunk', stock: 88, region: 'WW', sales: 178, rating_avg: 4.7, rating_count: 71 },
  { v: v7, cat: 'telecom', title: 'SIP Trunk — Bulk 5', subtitle: 'Wholesale tier',
    description: 'Bulk SIP trunk pack. 5 trunks, each with unlimited concurrency. US and international dialing. Load balancing ready.',
    price_usd: 780, unit: '5 pack', stock: 22, region: 'WW', sales: 44, rating_avg: 4.6, rating_count: 18 },
  { v: v7, cat: 'telecom', title: 'VoIP Number — International', subtitle: '40+ countries',
    description: 'International VoIP numbers across 40+ countries. Inbound SMS and voice. Route to any SIP endpoint. WebRTC compatible.',
    price_usd: 20, unit: 'number', stock: 999, region: 'WW', sales: 612, rating_avg: 4.5, rating_count: 244 },
  { v: v7, cat: 'telecom', title: 'Non-VoIP Number — Verified', subtitle: 'Real SIM, bypass VoIP detection',
    description: 'Non-VoIP number backed by a real SIM. Bypasses VoIP detection used by banks, Google, WhatsApp, and Telegram. Inbound SMS only.',
    price_usd: 45, unit: 'number', stock: 999, region: 'US', sales: 522, rating_avg: 4.7, rating_count: 217 },
  { v: v7, cat: 'telecom', title: 'Non-VoIP Number — Bulk 20', subtitle: 'Real SIM, wholesale',
    description: 'Bulk non-VoIP numbers. 20 real-SIM-backed numbers per pack. Full inbound SMS. Bypasses VoIP detection.',
    price_usd: 650, unit: '20 pack', stock: 34, region: 'US', sales: 89, rating_avg: 4.8, rating_count: 34 },
  { v: v7, cat: 'telecom', title: 'Non-VoIP Number — UK / EU', subtitle: 'Real SIM, verified',
    description: 'Non-VoIP numbers for UK and EU. Backed by real SIMs. Bypasses VoIP detection used by major banks and platforms.',
    price_usd: 55, unit: 'number', stock: 142, region: 'EU', sales: 267, rating_avg: 4.6, rating_count: 108 },
  { v: v7, cat: 'telecom', title: 'VoIP Number — Free Sample', subtitle: 'Preview tier',
    description: 'Single VoIP sample number. Preview routing and quality. 7-day duration. Test before committing to full service.',
    price_usd: 15, unit: 'sample', stock: 999, region: 'WW', sales: 512, rating_avg: 4.3, rating_count: 189 },
  { v: v7, cat: 'telecom', title: 'SIM Farm Access — 100 SIMs', subtitle: 'Physical rack, remote',
    description: 'Remote access to physical SIM farm. 100 active SIMs. US numbers. SMS and voice routing. Remote control panel. Monthly renewal.',
    price_usd: 780, unit: 'month', stock: 8, region: 'US', sales: 34, rating_avg: 4.6, rating_count: 14 },

  // ─── BYPASS / CAPTCHA / 2FA ──────────────────────────
  { v: v8, cat: 'bypass', title: 'reCAPTCHA v2 Bypass — Per 1k', subtitle: 'Token service',
    description: 'Google reCAPTCHA v2 bypass service. Returns valid tokens per request. 1000 tokens per bundle. Average solve time 12 seconds.',
    price_usd: 60, unit: 'per 1k', stock: 999, region: 'WW', sales: 812, rating_avg: 4.6, rating_count: 342 },
  { v: v8, cat: 'bypass', title: 'reCAPTCHA v3 Bypass — Per 1k', subtitle: 'Score 0.9+ tokens',
    description: 'Google reCAPTCHA v3 bypass. Returns high-score tokens (0.9+). 1000 tokens per bundle. Faster than human-solve services.',
    price_usd: 75, unit: 'per 1k', stock: 999, region: 'WW', sales: 512, rating_avg: 4.7, rating_count: 217 },
  { v: v8, cat: 'bypass', title: 'reCAPTCHA Enterprise Bypass', subtitle: 'Premium tier',
    description: 'Google reCAPTCHA Enterprise bypass. Handles enterprise-grade scoring. Per-token pricing. Bulk discount available.',
    price_usd: 180, unit: 'per 1k', stock: 244, region: 'WW', sales: 189, rating_avg: 4.7, rating_count: 76 },
  { v: v8, cat: 'bypass', title: 'hCaptcha Bypass — Per 1k', subtitle: 'Token service',
    description: 'hCaptcha bypass service. Returns valid tokens per request. 1000 tokens per bundle. Supports all hCaptcha difficulty levels.',
    price_usd: 55, unit: 'per 1k', stock: 999, region: 'WW', sales: 622, rating_avg: 4.6, rating_count: 254 },
  { v: v8, cat: 'bypass', title: 'Cloudflare Turnstile Bypass', subtitle: 'Token service',
    description: 'Cloudflare Turnstile bypass. Returns valid challenge tokens. 1000 tokens per bundle. Works with all sites using Turnstile.',
    price_usd: 90, unit: 'per 1k', stock: 999, region: 'WW', sales: 344, rating_avg: 4.6, rating_count: 128 },
  { v: v8, cat: 'bypass', title: 'CAPTCHA Farm — Full Setup', subtitle: 'Self-hosted',
    description: 'Self-hosted CAPTCHA farm setup. Includes scripts, proxies, and human-worker routing. Solves reCAPTCHA, hCaptcha, and image challenges.',
    price_usd: 620, unit: 'setup', stock: 12, region: 'WW', sales: 44, rating_avg: 4.6, rating_count: 18 },
  { v: v8, cat: 'bypass', title: 'reCAPTCHA Bypass — Starter 100', subtitle: 'Entry tier',
    description: 'Starter bundle. 100 reCAPTCHA v2 tokens. Preview the service before committing to bulk.',
    price_usd: 15, unit: 'per 100', stock: 999, region: 'WW', sales: 612, rating_avg: 4.4, rating_count: 244 },
  { v: v8, cat: 'bypass', title: 'SMS 2FA Bypass — Service', subtitle: 'Real-time intercept',
    description: 'Real-time SMS 2FA interception. Routes OTPs to your endpoint. Works with banks, exchanges, and platforms using SMS 2FA.',
    price_usd: 320, unit: 'month', stock: 88, region: 'WW', sales: 189, rating_avg: 4.7, rating_count: 76 },
  { v: v8, cat: 'bypass', title: 'Email 2FA Bypass — IMAP', subtitle: 'Inbox monitoring',
    description: 'Email 2FA bypass via IMAP monitoring. Extracts OTPs from target inbox in real time. Works with Gmail, Outlook, Yahoo, ProtonMail.',
    price_usd: 220, unit: 'month', stock: 142, region: 'WW', sales: 244, rating_avg: 4.6, rating_count: 98 },
  { v: v8, cat: 'bypass', title: 'TOTP Bypass — Session Hijack', subtitle: 'Cookie + token',
    description: 'TOTP bypass via session hijack. Steals auth cookies and session tokens from browser, bypasses TOTP 2FA entirely. Works on most platforms.',
    price_usd: 480, unit: 'license', stock: 44, region: 'WW', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v8, cat: 'bypass', title: 'KYC Bypass — AI Video Liveness', subtitle: 'Deepfake-style',
    description: 'KYC bypass service. AI-generated video liveness verification. Bypasses most KYC providers including Onfido, Jumio, Veriff, Sumsub.',
    price_usd: 780, unit: 'license', stock: 22, region: 'WW', sales: 67, rating_avg: 4.7, rating_count: 28 },
  { v: v8, cat: 'bypass', title: 'FingerprintJS Bypass', subtitle: 'Browser fingerprint',
    description: 'FingerprintJS bypass. Evades canvas, WebGL, and audio fingerprinting. Works with FingerprintJS Pro. Browser extension and script versions.',
    price_usd: 180, unit: 'license', stock: 142, region: 'WW', sales: 211, rating_avg: 4.6, rating_count: 87 },

  // ─── CVEs / EXPLOITS / VULNS ─────────────────────────
  { v: v6, cat: 'cve', title: 'CVE Database — Bulk Access', subtitle: 'Full feed, real-time',
    description: 'Full CVE database access. Real-time feed of new CVEs, exploits, and PoCs. Includes severity scoring, affected versions, and patch status.',
    price_usd: 120, unit: 'month', stock: 999, region: 'WW', sales: 388, rating_avg: 4.7, rating_count: 156 },
  { v: v6, cat: 'cve', title: '0-Day Exploit — Windows LPE', subtitle: 'Local privilege escalation',
    description: 'Windows local privilege escalation 0-day. Works on Win10 and Win11 fully patched. PoC and weaponized version included. Limited distribution.',
    price_usd: 800, unit: 'exploit', stock: 6, region: 'WW', sales: 14, rating_avg: 4.8, rating_count: 6 },
  { v: v6, cat: 'cve', title: '0-Day Exploit — Linux Kernel', subtitle: 'Container escape',
    description: 'Linux kernel container escape 0-day. Works on kernels 5.x and 6.x. Escapes Docker, Kubernetes, and LXC containers. Privilege escalation to host.',
    price_usd: 800, unit: 'exploit', stock: 4, region: 'WW', sales: 11, rating_avg: 4.9, rating_count: 5 },
  { v: v6, cat: 'cve', title: '0-Day Exploit — Chrome Renderer', subtitle: 'RCE via JS',
    description: 'Chrome renderer RCE 0-day. Remote code execution via crafted JavaScript. Works on current stable build. PoC included.',
    price_usd: 800, unit: 'exploit', stock: 3, region: 'WW', sales: 8, rating_avg: 4.9, rating_count: 4 },
  { v: v6, cat: 'cve', title: 'Exploit Kit — Browser', subtitle: 'Multi-CVE, all browsers',
    description: 'Browser exploit kit. Chains 6 CVEs targeting Chrome, Firefox, Edge, and Safari. Drive-by RCE. Includes admin panel for statistics.',
    price_usd: 780, unit: 'kit', stock: 12, region: 'WW', sales: 41, rating_avg: 4.7, rating_count: 18 },
  { v: v6, cat: 'cve', title: 'Exploit Kit — Office Documents', subtitle: 'Macro + OLE',
    description: 'Office exploit kit. Malicious Word/Excel documents using macro and OLE vulnerabilities. Multi-CVE. Works on Office 2016-2024. Bypasses most sandboxes.',
    price_usd: 620, unit: 'kit', stock: 22, region: 'WW', sales: 76, rating_avg: 4.6, rating_count: 31 },
  { v: v6, cat: 'cve', title: 'PoC Repository — Full Access', subtitle: 'Curated exploits',
    description: 'Curated PoC repository. 5000+ exploits across web, network, and local. Filterable by severity, CVE year, and affected software.',
    price_usd: 240, unit: 'access', stock: 142, region: 'WW', sales: 244, rating_avg: 4.6, rating_count: 98 },
  { v: v6, cat: 'cve', title: 'Vulnerability Scan — Target', subtitle: 'Custom scan report',
    description: 'Custom vulnerability scan against a specified target. Includes CVE list, severity scoring, exploitability analysis, and recommended attack paths.',
    price_usd: 180, unit: 'per scan', stock: 999, region: 'WW', sales: 267, rating_avg: 4.7, rating_count: 108 },
  { v: v6, cat: 'cve', title: 'CVE Analysis Report — Custom', subtitle: 'Deep dive',
    description: 'Custom CVE analysis. Deep dive into a specific CVE. Includes exploitability assessment, PoC, mitigation bypass notes, and weaponization.',
    price_usd: 320, unit: 'report', stock: 999, region: 'WW', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v6, cat: 'cve', title: 'CVE Alert Service — Daily', subtitle: 'Filtered feed',
    description: 'Daily CVE alerts filtered to your tech stack. Choose your OS, frameworks, and services. Get only the CVEs that matter to you.',
    price_usd: 45, unit: 'month', stock: 999, region: 'WW', sales: 512, rating_avg: 4.6, rating_count: 217 },
  { v: v6, cat: 'cve', title: 'Metasploit Module — Private', subtitle: 'Custom module',
    description: 'Private Metasploit module built for a specific target. Includes auxiliary scanner, exploit module, and post-exploitation payloads.',
    price_usd: 480, unit: 'module', stock: 34, region: 'WW', sales: 67, rating_avg: 4.7, rating_count: 28 },
  { v: v6, cat: 'cve', title: 'CVE Starter — Single Report', subtitle: 'Entry tier',
    description: 'Single CVE analysis report. Preview the quality of the CVE analysis service. Any CVE, standard report format.',
    price_usd: 15, unit: 'report', stock: 999, region: 'WW', sales: 344, rating_avg: 4.4, rating_count: 128 },

  // ─── ENROLLMENT & IDME ───────────────────────────────
  { v: v9, cat: 'enroll', title: 'ID.me Full Verification Kit', subtitle: 'Full identity + selfie bypass',
    description: 'Complete ID.me verification kit. Full identity docs, address proof, phone number, and video selfie package. Bypasses ID.me KYC for IRS, SSA, VA, and state portals.',
    price_usd: 320, unit: 'package', stock: 44, region: 'US', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v9, cat: 'enroll', title: 'ID.me Account — Pre-verified', subtitle: 'Ready to use',
    description: 'Pre-verified ID.me account. All documents matched. Phone and email active. Used for IRS, state benefits, and VA portal access.',
    price_usd: 240, unit: 'account', stock: 62, region: 'US', sales: 189, rating_avg: 4.6, rating_count: 78 },
  { v: v9, cat: 'enroll', title: 'Enrollment Package — University', subtitle: 'Full student setup',
    description: 'Full university enrollment package. Student identity, SSN, address, phone, high school transcript, and FAFSA pre-fill. Works with most US universities.',
    price_usd: 680, unit: 'package', stock: 18, region: 'US', sales: 76, rating_avg: 4.7, rating_count: 31 },
  { v: v9, cat: 'enroll', title: 'College Application Kit — Premium', subtitle: 'Common App ready',
    description: 'College application kit. Common App-compatible identity. Includes essays, transcripts, recommendations, and enrollment deposit routing.',
    price_usd: 780, unit: 'kit', stock: 12, region: 'US', sales: 41, rating_avg: 4.8, rating_count: 18 },
  { v: v9, cat: 'enroll', title: 'ID.me Verif — Single Doc', subtitle: 'Entry tier',
    description: 'Single ID.me verification doc. Government ID only. Preview tier for testing the process.',
    price_usd: 25, unit: 'doc', stock: 999, region: 'US', sales: 344, rating_avg: 4.4, rating_count: 128 },
  { v: v9, cat: 'enroll', title: 'Student Email + .edu Access', subtitle: 'Active inbox',
    description: 'Active .edu student email. University inbox with full access. Includes student portal login. Unlocks student discounts and services.',
    price_usd: 40, unit: 'account', stock: 142, region: 'US', sales: 456, rating_avg: 4.6, rating_count: 178 },

  // ─── TRANSCRIPTS & DIPLOMAS ──────────────────────────
  { v: v10, cat: 'transcripts', title: 'High School Transcript — Verified', subtitle: 'Any US state',
    description: 'Verified high school transcript. Any US state. Includes GPA, graduation date, and official seal. Print and scan-ready.',
    price_usd: 120, unit: 'transcript', stock: 244, region: 'US', sales: 344, rating_avg: 4.6, rating_count: 142 },
  { v: v10, cat: 'transcripts', title: 'College Transcript — Bulk 5', subtitle: 'Multi-university',
    description: 'Bulk college transcripts. 5 transcripts across different universities. Includes GPA, credits, and degree conferral.',
    price_usd: 480, unit: '5 pack', stock: 44, region: 'US', sales: 88, rating_avg: 4.7, rating_count: 34 },
  { v: v10, cat: 'transcripts', title: 'GED Certificate + Transcript', subtitle: 'State-issued look',
    description: 'GED certificate with matching transcript. State-issued look. Includes test scores and completion date.',
    price_usd: 180, unit: 'set', stock: 122, region: 'US', sales: 178, rating_avg: 4.5, rating_count: 71 },
  { v: v10, cat: 'transcripts', title: 'Diploma Package — Full Set', subtitle: 'HS + college',
    description: 'Full diploma package. High school diploma and college degree. Matching transcripts for both. Print-ready.',
    price_usd: 620, unit: 'package', stock: 34, region: 'US', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v10, cat: 'transcripts', title: 'Transcript Template — Editable', subtitle: 'PSD, any school',
    description: 'Editable transcript template. Photoshop PSD format. Layers for school name, GPA, courses, and dates. Any US school.',
    price_usd: 40, unit: 'template', stock: 999, region: 'US', sales: 388, rating_avg: 4.6, rating_count: 156 },
  { v: v10, cat: 'transcripts', title: 'Transcript Sample — Single', subtitle: 'Preview tier',
    description: 'Single sample transcript. Preview quality and format. Low-cost trial before bulk purchase.',
    price_usd: 15, unit: 'sample', stock: 999, region: 'US', sales: 512, rating_avg: 4.4, rating_count: 189 },

  // ─── FLASHERS & FAKE FUNDS ───────────────────────────
  { v: v11, cat: 'flasher', title: 'USDT Flash — 10k Flash', subtitle: 'Bitflasher, 24h window',
    description: 'USDT flasher via Bitflasher protocol. 10,000 USDT flashed for 24-hour window. Visible on-chain, confirmable in wallet, expires after window.',
    price_usd: 180, unit: 'flash', stock: 999, region: 'WW', sales: 244, rating_avg: 4.5, rating_count: 98 },
  { v: v11, cat: 'flasher', title: 'USDT Flash — 100k Flash', subtitle: 'Bitflasher, 48h window',
    description: 'USDT flasher. 100,000 USDT for 48-hour window. Extendable. Works on TRC-20, ERC-20, and BEP-20 chains.',
    price_usd: 620, unit: 'flash', stock: 44, region: 'WW', sales: 122, rating_avg: 4.6, rating_count: 51 },
  { v: v11, cat: 'flasher', title: 'USDT Flash — Bulk 1M', subtitle: 'Bitflasher, wholesale',
    description: 'Bulk USDT flash. 1,000,000 USDT for 72-hour window. Multi-chain support. Includes wallet routing scripts.',
    price_usd: 800, unit: 'flash', stock: 8, region: 'WW', sales: 34, rating_avg: 4.7, rating_count: 14 },
  { v: v11, cat: 'flasher', title: 'BTC Flash — 5 BTC', subtitle: 'Bitflasher, 24h window',
    description: 'BTC flasher. 5 BTC for 24-hour window. Visible on-chain, confirmable, expires. Includes wallet scripts.',
    price_usd: 480, unit: 'flash', stock: 22, region: 'WW', sales: 67, rating_avg: 4.5, rating_count: 28 },
  { v: v11, cat: 'flasher', title: 'Fake Bank Transfer Screenshot', subtitle: 'Any bank, any amount',
    description: 'Fake bank transfer screenshots. Any US or UK bank. Any amount. Realistic formatting including transaction IDs and confirmation numbers.',
    price_usd: 20, unit: 'screenshot', stock: 999, region: 'WW', sales: 892, rating_avg: 4.5, rating_count: 342 },
  { v: v11, cat: 'flasher', title: 'Fake Balance Screenshot — Bulk 10', subtitle: 'Any wallet or bank',
    description: 'Bulk fake balance screenshots. 10 images per pack. Any crypto wallet or bank. Realistic UI matching current app versions.',
    price_usd: 90, unit: '10 pack', stock: 244, region: 'WW', sales: 267, rating_avg: 4.4, rating_count: 108 },
  { v: v11, cat: 'flasher', title: 'Fake Payment Gateway — Full Setup', subtitle: 'Self-hosted',
    description: 'Self-hosted fake payment gateway. Shows checkout pages that accept crypto, then displays "payment received". Full admin panel.',
    price_usd: 780, unit: 'setup', stock: 8, region: 'WW', sales: 41, rating_avg: 4.6, rating_count: 18 },
  { v: v11, cat: 'flasher', title: 'Flash Sample — Trial', subtitle: 'Entry tier',
    description: 'Single small flash. 100 USDT for 6-hour window. Test the flasher before bulk purchase.',
    price_usd: 15, unit: 'flash', stock: 999, region: 'WW', sales: 512, rating_avg: 4.3, rating_count: 189 },

  // ─── JAILBREAKS & UNLOCKS ────────────────────────────
  { v: v12, cat: 'jailbreak', title: 'iOS Jailbreak — Full Tool', subtitle: 'iPhone 8 to 15',
    description: 'Full iOS jailbreak tool. Supports iPhone 8 through iPhone 15. Works on iOS 14 to 17.6. Includes Cydia, Sileo, and rootless package manager.',
    price_usd: 120, unit: 'tool', stock: 999, region: 'WW', sales: 344, rating_avg: 4.6, rating_count: 128 },
  { v: v12, cat: 'jailbreak', title: 'Android Root — Universal Tool', subtitle: 'All major brands',
    description: 'Universal Android root tool. Supports Samsung, Xiaomi, OnePlus, Pixel, and Motorola. One-click root via USB. Includes Magisk and SuperSU.',
    price_usd: 80, unit: 'tool', stock: 999, region: 'WW', sales: 422, rating_avg: 4.7, rating_count: 178 },
  { v: v12, cat: 'jailbreak', title: 'iCloud Bypass — Activation Lock', subtitle: 'All iPhone models',
    description: 'iCloud activation lock bypass. All iPhone models. Removes Find My iPhone lock. Persistent across reboots and iOS updates.',
    price_usd: 220, unit: 'license', stock: 142, region: 'WW', sales: 189, rating_avg: 4.6, rating_count: 78 },
  { v: v12, cat: 'jailbreak', title: 'Carrier Unlock — iPhone', subtitle: 'Any carrier',
    description: 'iPhone carrier unlock. Any carrier, any model. Permanent unlock via IMEI. Works on iPhone 6 through 15.',
    price_usd: 60, unit: 'unlock', stock: 999, region: 'WW', sales: 622, rating_avg: 4.7, rating_count: 244 },
  { v: v12, cat: 'jailbreak', title: 'Carrier Unlock — Android', subtitle: 'Any carrier, bulk',
    description: 'Android carrier unlock. Any carrier, any model. IMEI-based. Bulk pricing available for 10+ devices.',
    price_usd: 40, unit: 'unlock', stock: 999, region: 'WW', sales: 512, rating_avg: 4.5, rating_count: 217 },
  { v: v12, cat: 'jailbreak', title: 'FRP Bypass — Samsung / Google', subtitle: 'Android factory reset',
    description: 'FRP (Factory Reset Protection) bypass. Samsung and Google devices. Removes Google account lock after factory reset.',
    price_usd: 90, unit: 'license', stock: 244, region: 'WW', sales: 267, rating_avg: 4.6, rating_count: 108 },
  { v: v12, cat: 'jailbreak', title: 'Console Jailbreak — PS5', subtitle: 'All firmwares',
    description: 'PS5 jailbreak. All firmwares up to 4.51. Homebrew support, custom packages, backup loading. Includes exploit chain and instructions.',
    price_usd: 480, unit: 'tool', stock: 44, region: 'WW', sales: 122, rating_avg: 4.7, rating_count: 51 },
  { v: v12, cat: 'jailbreak', title: 'Nintendo Switch CFW Install', subtitle: 'Full jailbreak',
    description: 'Nintendo Switch custom firmware install. Atmosphère CFW, homebrew menu, backup loading. Full guide and files. Works on V1 and V2.',
    price_usd: 220, unit: 'license', stock: 244, region: 'WW', sales: 189, rating_avg: 4.6, rating_count: 78 },
  { v: v12, cat: 'jailbreak', title: 'Jailbreak Sample — Preview', subtitle: 'Entry tier',
    description: 'Single device preview jailbreak. Older model only. Preview the service before committing to newer devices.',
    price_usd: 15, unit: 'license', stock: 999, region: 'WW', sales: 344, rating_avg: 4.3, rating_count: 128 },

  // ─── DRUGS & PHARMACEUTICALS ─────────────────────────
  { v: v13, cat: 'drugs', title: 'Pharmaceutical — Starter Pack', subtitle: 'Common meds',
    description: 'Starter pharmaceutical pack. Assorted common prescription meds. Shipped discreetly. Domestic US shipping 2-4 days.',
    price_usd: 60, unit: 'pack', stock: 999, region: 'US', sales: 456, rating_avg: 4.5, rating_count: 178 },
  { v: v13, cat: 'drugs', title: 'Prescription Painkillers — Bulk 100', subtitle: 'Oxy, Hydro, Codeine',
    description: 'Bulk prescription painkillers. 100 units per pack. Oxycodone, Hydrocodone, Codeine mixes available. Domestic and international shipping.',
    price_usd: 520, unit: '100 pack', stock: 62, region: 'US', sales: 211, rating_avg: 4.6, rating_count: 84 },
  { v: v13, cat: 'drugs', title: 'Benzodiazepines — Bulk 200', subtitle: 'Xanax, Valium, Klonopin',
    description: 'Bulk benzodiazepines. 200 units per pack. Xanax, Valium, Klonopin, Ativan mixes. Pharmaceutical-grade.',
    price_usd: 420, unit: '200 pack', stock: 88, region: 'US', sales: 267, rating_avg: 4.6, rating_count: 108 },
  { v: v13, cat: 'drugs', title: 'Stimulants — Pharmaceutical', subtitle: 'Adderall, Ritalin',
    description: 'Pharmaceutical stimulants. Adderall, Ritalin, Vyvanse. Various dosages available. Prescription-grade.',
    price_usd: 340, unit: '100 pack', stock: 122, region: 'US', sales: 178, rating_avg: 4.5, rating_count: 71 },
  { v: v13, cat: 'drugs', title: 'Psychedelics — LSD Blotters', subtitle: 'Vials and sheets',
    description: 'LSD blotters. Various strengths available. 100-blotter sheets or single vials. Discreet shipping.',
    price_usd: 380, unit: 'sheet', stock: 44, region: 'US', sales: 133, rating_avg: 4.7, rating_count: 51 },
  { v: v13, cat: 'drugs', title: 'MDMA / Ecstasy — Bulk', subtitle: 'Crystal or pills',
    description: 'MDMA crystal or ecstasy pills. Bulk pricing. Tested purity. Domestic and international shipping. Minimum 10g crystal or 100 pills.',
    price_usd: 480, unit: 'bulk', stock: 34, region: 'WW', sales: 122, rating_avg: 4.6, rating_count: 51 },
  { v: v13, cat: 'drugs', title: 'Cannabis — Premium Flower', subtitle: 'Various strains',
    description: 'Premium cannabis flower. Various strains. Indoor grown. Discreet shipping. Minimum 1oz. Lab-tested.',
    price_usd: 220, unit: 'oz', stock: 122, region: 'US', sales: 344, rating_avg: 4.7, rating_count: 142 },
  { v: v13, cat: 'drugs', title: 'Prescription Pad — Blank', subtitle: 'Any US state',
    description: 'Blank prescription pads. Any US state. Realistic formatting. Match with prescriber info. Print-ready.',
    price_usd: 120, unit: 'pad', stock: 244, region: 'US', sales: 267, rating_avg: 4.5, rating_count: 108 },
  { v: v13, cat: 'drugs', title: 'Pharmacy Login — Verified', subtitle: 'Retail chain access',
    description: 'Verified pharmacy logins. Major US retail chains. Pharmacist and technician accounts. Access to inventory, prescription processing, and customer records.',
    price_usd: 620, unit: 'access', stock: 22, region: 'US', sales: 88, rating_avg: 4.7, rating_count: 34 },
  { v: v13, cat: 'drugs', title: 'Drug Sample — Trial', subtitle: 'Entry tier',
    description: 'Sample trial pack. Small quantity of a common pharmaceutical. Preview quality before bulk.',
    price_usd: 15, unit: 'sample', stock: 999, region: 'US', sales: 512, rating_avg: 4.4, rating_count: 189 },

  // ─── HACKERS FOR HIRE ────────────────────────────────
  { v: v14, cat: 'hire', title: 'Hacker — Single Target Access', subtitle: 'Email or social',
    description: 'Single target access service. Email or social media account compromise. Full credentials delivered. 24-72 hour turnaround.',
    price_usd: 220, unit: 'per target', stock: 999, region: 'WW', sales: 189, rating_avg: 4.6, rating_count: 78 },
  { v: v14, cat: 'hire', title: 'Hacker — Phone Compromise', subtitle: 'iOS or Android',
    description: 'Phone compromise service. iOS or Android target. Full remote access, messages, calls, location, and camera. Persistent access.',
    price_usd: 620, unit: 'per target', stock: 142, region: 'WW', sales: 122, rating_avg: 4.6, rating_count: 51 },
  { v: v14, cat: 'hire', title: 'Hacker — Bank Account Access', subtitle: 'US or EU bank',
    description: 'Bank account compromise. US or EU target. Full balance access, transfer capability, and transaction history. Includes 2FA bypass.',
    price_usd: 780, unit: 'per target', stock: 88, region: 'WW', sales: 67, rating_avg: 4.7, rating_count: 28 },
  { v: v14, cat: 'hire', title: 'Hacker — Website Takeover', subtitle: 'Any CMS',
    description: 'Website takeover service. WordPress, Shopify, custom CMS. Full admin access, database dump, and backdoor persistence.',
    price_usd: 480, unit: 'per site', stock: 122, region: 'WW', sales: 133, rating_avg: 4.7, rating_count: 51 },
  { v: v14, cat: 'hire', title: 'Hacker — DDoS Attack', subtitle: 'Custom duration',
    description: 'DDoS attack service. Any target, any duration. 500 Gbps peak capacity. Multi-vector. Includes TCP, UDP, and application-layer.',
    price_usd: 180, unit: 'per hour', stock: 999, region: 'WW', sales: 344, rating_avg: 4.5, rating_count: 142 },
  { v: v14, cat: 'hire', title: 'Hacker — Social Media Hijack', subtitle: 'All platforms',
    description: 'Social media account hijack. Instagram, Facebook, TikTok, Twitter, Snapchat. Full account takeover with recovery info.',
    price_usd: 260, unit: 'per account', stock: 244, region: 'WW', sales: 267, rating_avg: 4.6, rating_count: 108 },
  { v: v14, cat: 'hire', title: 'Hacker — Corporate Espionage', subtitle: 'Retainer',
    description: 'Corporate espionage service. Retainer-based. Email compromise, internal document extraction, competitor intelligence. Custom scoping.',
    price_usd: 800, unit: 'per week', stock: 8, region: 'WW', sales: 22, rating_avg: 4.8, rating_count: 9 },
  { v: v14, cat: 'hire', title: 'Hacker Team — Full Ops', subtitle: 'Dedicated crew',
    description: 'Dedicated hacker team for sustained operations. 5+ operators. Custom target scope, long-term persistence, exit strategy. Monthly retainer.',
    price_usd: 800, unit: 'per month', stock: 4, region: 'WW', sales: 14, rating_avg: 4.9, rating_count: 6 },
  { v: v14, cat: 'hire', title: 'Hire Consultation — 30 min', subtitle: 'Entry tier',
    description: '30-minute consultation with a hacker. Scope your target, get a quote, understand feasibility. Non-refundable.',
    price_usd: 15, unit: 'session', stock: 999, region: 'WW', sales: 512, rating_avg: 4.4, rating_count: 189 },
  { v: v14, cat: 'hire', title: 'Hacker — Bug Bounty Report', subtitle: 'Custom scan',
    description: 'Custom bug bounty report for a target site. Includes vulnerability list, severity scoring, PoC screenshots, and remediation notes.',
    price_usd: 320, unit: 'report', stock: 244, region: 'WW', sales: 122, rating_avg: 4.6, rating_count: 51 },

  // ─── DOCUMENTS & CERTIFICATES ────────────────────────
  { v: v10, cat: 'docs', title: 'Birth Certificate — Any US State', subtitle: 'Print-ready',
    description: 'Birth certificate. Any US state. Includes state seal and registrar signature. Print and scan-ready.',
    price_usd: 120, unit: 'doc', stock: 244, region: 'US', sales: 388, rating_avg: 4.6, rating_count: 156 },
  { v: v10, cat: 'docs', title: 'Marriage Certificate — Custom', subtitle: 'Any state, any names',
    description: 'Marriage certificate. Any state, any names, any date. Includes officiant signature and state seal.',
    price_usd: 140, unit: 'doc', stock: 244, region: 'US', sales: 267, rating_avg: 4.5, rating_count: 108 },
  { v: v10, cat: 'docs', title: 'Death Certificate — Print-ready', subtitle: 'Any state',
    description: 'Death certificate. Any US state. Includes coroner signature and state seal. Used for estate and insurance purposes.',
    price_usd: 160, unit: 'doc', stock: 122, region: 'US', sales: 178, rating_avg: 4.5, rating_count: 71 },
  { v: v10, cat: 'docs', title: 'SSN Card — Physical', subtitle: 'Shipped discreetly',
    description: 'Physical SSN card. Realistic paper stock. Shipped discreetly via standard mail. Domestic US shipping included.',
    price_usd: 80, unit: 'card', stock: 388, region: 'US', sales: 456, rating_avg: 4.6, rating_count: 178 },
  { v: v10, cat: 'docs', title: 'Professional Certificate — Any Field', subtitle: 'Any issuer',
    description: 'Professional certificates. Any field, any issuer. IT, medical, trades, finance. Realistic formatting with seals and signatures.',
    price_usd: 180, unit: 'cert', stock: 244, region: 'WW', sales: 267, rating_avg: 4.5, rating_count: 108 },
  { v: v10, cat: 'docs', title: 'Notary Stamp + Signature', subtitle: 'Realistic replica',
    description: 'Notary stamp and signature package. Realistic replica stamp. Includes notary name, commission number, and state.',
    price_usd: 90, unit: 'set', stock: 388, region: 'US', sales: 344, rating_avg: 4.6, rating_count: 142 },
  { v: v10, cat: 'docs', title: 'Apostille + Authentication', subtitle: 'Hague-compliant',
    description: 'Apostille authentication for any document. Hague Convention compliant. Realistic formatting. For international use.',
    price_usd: 220, unit: 'doc', stock: 122, region: 'WW', sales: 122, rating_avg: 4.6, rating_count: 51 },
  { v: v10, cat: 'docs', title: 'Document Template — Any Type', subtitle: 'PSD, editable',
    description: 'Editable document template. Photoshop PSD. Any type — birth, marriage, death, diploma, certificate. Layers for all fields.',
    price_usd: 50, unit: 'template', stock: 999, region: 'US', sales: 512, rating_avg: 4.6, rating_count: 217 },
  { v: v10, cat: 'docs', title: 'Doc Sample — Preview', subtitle: 'Entry tier',
    description: 'Single sample document. Preview formatting and quality. Low-cost trial.',
    price_usd: 15, unit: 'sample', stock: 999, region: 'US', sales: 622, rating_avg: 4.4, rating_count: 244 }
];

const insert = db.prepare(`
  INSERT INTO listings
    (vendor_id, category_id, title, subtitle, description, price_usd, unit, stock, region,
     ships_from, status, sales, rating_avg, rating_count)
  VALUES (?, (SELECT id FROM categories WHERE slug = ?), ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?, ?)
`);

const update = db.prepare(`
  UPDATE listings
  SET price_usd = ?, unit = ?, stock = ?, region = ?, subtitle = ?, description = ?
  WHERE id = ?
`);

let added = 0;
let updated = 0;
for (const l of LISTINGS) {
  const existing = db.prepare(
    `SELECT id FROM listings WHERE vendor_id = ? AND title = ?`
  ).get(l.v.id, l.title);
  if (existing) {
    update.run(
      l.price_usd, l.unit, l.stock || 100, l.region || 'WW',
      l.subtitle || null, l.description, existing.id
    );
    updated++;
    continue;
  }
  insert.run(
    l.v.id, l.cat, l.title, l.subtitle || null, l.description,
    l.price_usd, l.unit, l.stock || 100, l.region || 'WW',
    l.ships_from || 'WW', l.sales || 0, l.rating_avg || 4.6, l.rating_count || 20
  );
  added++;
}

console.log('seeded', {
  added,
  updated,
  users: db.prepare(`SELECT COUNT(*) c FROM users`).get().c,
  listings: db.prepare(`SELECT COUNT(*) c FROM listings`).get().c,
  categories: db.prepare(`SELECT COUNT(*) c FROM categories`).get().c,
  price_min: db.prepare(`SELECT MIN(price_usd) m FROM listings`).get().m,
  price_max: db.prepare(`SELECT MAX(price_usd) m FROM listings`).get().m
});
